# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: resume_action.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'resume_action.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13resume_action.proto\x12\x10resume.action.v2\"c\n\x12\x41pplyAccessRequest\x12\x15\n\rapplicant_uid\x18\x01 \x01(\t\x12\x12\n\ntarget_uid\x18\x02 \x01(\t\x12\x11\n\tresume_id\x18\x03 \x01(\t\x12\x0f\n\x07purpose\x18\x04 \x01(\t\"I\n\x0fPermissionCheck\x12\x11\n\tactor_uid\x18\x01 \x01(\t\x12\x0e\n\x06\x61\x63tion\x18\x02 \x01(\t\x12\x13\n\x0bresource_id\x18\x03 \x01(\t\"F\n\x0e\x41\x63tionResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x12\n\nerror_code\x18\x03 \x01(\x05\x32\xca\x01\n\x13ResumeActionService\x12[\n\x11\x41pplyResumeAccess\x12$.resume.action.v2.ApplyAccessRequest\x1a .resume.action.v2.ActionResponse\x12V\n\x0f\x43heckPermission\x12!.resume.action.v2.PermissionCheck\x1a .resume.action.v2.ActionResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'resume_action_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_APPLYACCESSREQUEST']._serialized_start=41
  _globals['_APPLYACCESSREQUEST']._serialized_end=140
  _globals['_PERMISSIONCHECK']._serialized_start=142
  _globals['_PERMISSIONCHECK']._serialized_end=215
  _globals['_ACTIONRESPONSE']._serialized_start=217
  _globals['_ACTIONRESPONSE']._serialized_end=287
  _globals['_RESUMEACTIONSERVICE']._serialized_start=290
  _globals['_RESUMEACTIONSERVICE']._serialized_end=492
# @@protoc_insertion_point(module_scope)
