# Generated by Django 5.2.4 on 2025-07-30 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('resume_id', models.IntegerField(primary_key=True, serialize=False, unique=True, verbose_name='简历ID')),
                ('category', models.CharField(choices=[('技术', '技术'), ('产品', '产品'), ('运营', '运营'), ('市场', '市场'), ('销售', '销售'), ('人力资源', '人力资源'), ('财务', '财务')], max_length=20, verbose_name='求职岗位类别')),
                ('title', models.CharField(max_length=200, verbose_name='简历标题')),
                ('desc', models.TextField(verbose_name='简历描述（期望薪资/城市等）')),
                ('photo', models.URLField(blank=True, null=True, verbose_name='照片URL')),
                ('email', models.EmailField(max_length=254, verbose_name='联系邮箱')),
                ('name', models.CharField(max_length=50, verbose_name='姓名')),
                ('education', models.JSONField(verbose_name='教育经历')),
                ('work_experience', models.JSONField(verbose_name='工作经历')),
                ('project_experience', models.JSONField(verbose_name='项目经历')),
                ('skill', models.JSONField(verbose_name='技能列表')),
                ('introduction', models.TextField(verbose_name='个人介绍')),
                ('address', models.TextField(verbose_name='联系地址')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '简历',
                'verbose_name_plural': '简历',
                'ordering': ['-created_at'],
            },
        ),
    ]
