# Generated by Django 5.2.4 on 2025-07-30 02:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('job_id', models.IntegerField(primary_key=True, serialize=False, unique=True, verbose_name='职位ID')),
                ('job_title', models.CharField(max_length=200, verbose_name='职位名称')),
                ('company_name', models.CharField(max_length=100, verbose_name='公司名称')),
                ('city', models.CharField(max_length=50, verbose_name='工作城市')),
                ('province', models.CharField(max_length=50, verbose_name='所在省份')),
                ('country', models.CharField(max_length=50, verbose_name='所在国家')),
                ('salary_range', models.CharField(max_length=20, verbose_name='薪资范围（如18k-25k）')),
                ('salary_low', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='薪资下限（k）')),
                ('salary_high', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='薪资上限（k）')),
                ('job_description', models.TextField(verbose_name='职位描述')),
                ('requirements', models.TextField(verbose_name='职位要求')),
                ('job_category', models.CharField(choices=[('技术', '技术'), ('产品', '产品'), ('运营', '运营'), ('市场', '市场'), ('销售', '销售'), ('人力资源', '人力资源'), ('财务', '财务')], max_length=20, verbose_name='职位类别')),
                ('minimum_work_time', models.CharField(max_length=20, verbose_name='最低工作年限（如3年）')),
                ('job_sort', models.CharField(choices=[('全职', '全职'), ('兼职', '兼职'), ('实习', '实习'), ('远程', '远程')], max_length=10, verbose_name='工作类型')),
                ('required_skills', models.JSONField(verbose_name='要求的技能列表')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '职位',
                'verbose_name_plural': '职位',
                'ordering': ['-created_at'],
            },
        ),
    ]
